version: "3.8"

services:
  scheduler:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
